language: go

go:
  - "1.12"

dist: xenial

git:
  depth: 1

env:
  - GO111MODULE=on

before_install:
  - sudo apt-get update
  - sudo apt install -y libzmq3-dev

script:
  - make

# Added comment - 
