# This example config contains all avaliable configuration options.
# Options are assigned their default or left blank with a FIXME: mark.


# ---- needed for both the API and the daemon ----
[redis]
host = ""                 # FIXME:
port = "6379"             # FIXME:
passwd = ""               # FIXME:
connection = "redis"


# ---- needed only for the API ----
[api]
port = "23485" # this needs to be a string
production = true


# ---- needed only for the deamon ----

# Needed when fetching via REST interface
[bitcoind.rest]
protocol = "http"
host = "localhost"
port = "8332"
responseTimeout = 30      # seconds

# Needed when fetching via JSON-RPC interface
[bitcoind.jsonrpc]
protocol = "http"
host = "localhost"
port = "8332" # regtest 18443 # testnet 18332
username = ""
password = ""
responseTimeout = 30 # seconds

[mempool]
enable = false            # enable mempool fetching
fetchInterface = "REST"   # fetch mempool via REST or JSON-RPC
fetchInterval = 60        # seconds
callSaveMempool = true    # calls the savemempool RPC on average after every fourth fetch  
  [mempool.processing]
  processCurrentMempool = true
  processHistoricalMempool = true
  processTransactionStats = true

[feeratefetcher]
enable = false
fetchInterval = 180

[log]
enableTrace = false
colorizeOutput = true

[zmq]
enable = false            # enable the zmq interface
host = "localhost"        # currently only tcp connections are supported 
port = "28332"
  [zmq.subscribeTo]       
  rawTx     = false
  rawBlock  = true        # needed to write recentBlocks to database 
  hashTx    = false
  hashBlock = false
  rawTx2    = false       # this needs a custom bitcoind patch https://github.com/0xB10C/bitcoin/tree/2019-06-rawtx2-zmq-for-memod to work 
